kind: PersistentVolume
apiVersion: v1
metadata:
  name: postgres-pv-claim
  
spec:
  storageClassName: slow
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/var/lib/postgresql/data"
